name: burger-briefing
on:
  schedule:
    - cron: "30 23 * * *"   # 08:30 KST
  workflow_dispatch: {}
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt
      - name: Set env
        run: |
          echo "SLACK_WEBHOOK=${{ secrets.SLACK_WEBHOOK }}" >> $GITHUB_ENV
          echo "TZ=Asia/Seoul" >> $GITHUB_ENV
      - run: python main.py
